"""initial schema

Revision ID: 291a36a43c80
Revises:
Create Date: 2026-09-25 03:49:30.223799

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "291a36a43c80"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column(
            "language", sa.String(length=10), server_default="pt-BR", nullable=False
        ),
        sa.Column("document_type", sa.String(length=20), nullable=True),
        sa.Column("document_number", sa.String(length=50), nullable=True),
        sa.Column("document_country", sa.String(length=2), nullable=True),
        sa.Column(
            "reliability_points", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "phone ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f("ck_client_phone_e164")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint(
            "document_country",
            "document_type",
            "document_number",
            name=op.f("uq_client_document_country"),
        ),
        sa.UniqueConstraint("email", name=op.f("uq_client_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_client_phone")),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "specifications",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "min_rental_days", sa.SmallInteger(), server_default="1", nullable=False
        ),
        sa.Column(
            "max_rental_days", sa.SmallInteger(), server_default="30", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('camera', 'lens', 'lighting', 'audio', 'accessory')",
            name=op.f("ck_product_category_valid"),
        ),
        sa.CheckConstraint(
            "max_rental_days >= min_rental_days", name=op.f("ck_product_max_gte_min")
        ),
        sa.CheckConstraint(
            "min_rental_days >= 1", name=op.f("ck_product_min_days_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("sku", name=op.f("uq_product_sku")),
    )
    op.create_table(
        "store",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("time_zone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store")),
    )
    op.create_table(
        "product_photo",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("position", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("alt_text", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_photo_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_photo")),
        sa.UniqueConstraint(
            "product_id", "position", name=op.f("uq_product_photo_product_id")
        ),
    )
    op.create_table(
        "product_price",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("daily_rate_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "daily_rate_cents > 0", name=op.f("ck_product_price_rate_positive")
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from",
            name=op.f("ck_product_price_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_price_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_price")),
    )
    op.create_table(
        "reservation",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("pickup_store_id", sa.Uuid(), nullable=False),
        sa.Column("return_store_id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('web_voice', 'phone', 'whatsapp')",
            name=op.f("ck_reservation_channel_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'confirmed', 'picked_up', 'returned', 'cancelled', 'expired')",
            name=op.f("ck_reservation_status_valid"),
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_reservation_valid_period")
        ),
        sa.ForeignKeyConstraint(
            ["client_id"], ["client.id"], name=op.f("fk_reservation_client_id_client")
        ),
        sa.ForeignKeyConstraint(
            ["pickup_store_id"],
            ["store.id"],
            name=op.f("fk_reservation_pickup_store_id_store"),
        ),
        sa.ForeignKeyConstraint(
            ["return_store_id"],
            ["store.id"],
            name=op.f("fk_reservation_return_store_id_store"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation")),
    )
    op.create_table(
        "unit",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column(
            "condition", sa.String(length=20), server_default="new", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("acquired_at", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "condition IN ('new', 'excellent', 'good', 'fair')",
            name=op.f("ck_unit_condition_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'sold', 'lost', 'retired')",
            name=op.f("ck_unit_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_unit_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["store.id"], name=op.f("fk_unit_store_id_store")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_unit_serial_number")),
    )
    op.create_table(
        "maintenance",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost_cents", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.CheckConstraint(
            "(cost_cents IS NULL) = (currency IS NULL)",
            name=op.f("ck_maintenance_cost_has_currency"),
        ),
        sa.CheckConstraint(
            "cost_cents IS NULL OR cost_cents >= 0",
            name=op.f("ck_maintenance_cost_positive"),
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > starts_at",
            name=op.f("ck_maintenance_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["unit.id"], name=op.f("fk_maintenance_unit_id_unit")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance")),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "kind IN ('rental', 'deposit', 'penalty')",
            name=op.f("ck_payment_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'declined', 'refunded')",
            name=op.f("ck_payment_status_valid"),
        ),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_payment_amount_positive")),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
            name=op.f("fk_payment_reservation_id_reservation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
        sa.UniqueConstraint(
            "provider", "external_id", name=op.f("uq_payment_provider")
        ),
    )
    op.create_table(
        "reservation_item",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("daily_rate_cents", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "daily_rate_cents > 0", name=op.f("ck_reservation_item_rate_positive")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
            name=op.f("fk_reservation_item_reservation_id_reservation"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["unit.id"], name=op.f("fk_reservation_item_unit_id_unit")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_item")),
        sa.UniqueConstraint(
            "reservation_id", "unit_id", name=op.f("uq_reservation_item_reservation_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservation_item")
    op.drop_table("payment")
    op.drop_table("maintenance")
    op.drop_table("unit")
    op.drop_table("reservation")
    op.drop_table("product_price")
    op.drop_table("product_photo")
    op.drop_table("store")
    op.drop_table("product")
    op.drop_table("client")
    # ### end Alembic commands ###
