"""one active payment per reservation kind

Revision ID: 8c26ce0bca84
Revises: c28bd31fb9dd
Create Date: 2026-10-01 06:51:05.856457

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c26ce0bca84"
down_revision: str | Sequence[str] | None = "c28bd31fb9dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_payment_one_active_per_reservation_kind",
        "payment",
        ["reservation_id", "kind"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'approved')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_payment_one_active_per_reservation_kind",
        table_name="payment",
        postgresql_where=sa.text("status IN ('pending', 'approved')"),
    )
    # ### end Alembic commands ###
