"""unit_block

Revision ID: ae65ba254314
Revises: 291a36a43c80
Create Date: 2026-09-26 22:04:14.672658

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae65ba254314"
down_revision: str | Sequence[str] | None = "291a36a43c80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_block",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("period", postgresql.DATERANGE(), nullable=False),
        sa.Column("reservation_item_id", sa.Uuid(), nullable=True),
        sa.Column("maintenance_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("unit_id"), "="),
            (sa.column("period"), "&&"),
            using="gist",
            name="unit_block_no_overlap",
        ),
        sa.CheckConstraint(
            "(reservation_item_id IS NULL) <> (maintenance_id IS NULL)",
            name=op.f("ck_unit_block_exactly_one_source"),
        ),
        sa.CheckConstraint(
            "NOT isempty(period) AND NOT lower_inf(period)",
            name=op.f("ck_unit_block_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["maintenance_id"],
            ["maintenance.id"],
            name=op.f("fk_unit_block_maintenance_id_maintenance"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_item_id"],
            ["reservation_item.id"],
            name=op.f("fk_unit_block_reservation_item_id_reservation_item"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["unit.id"], name=op.f("fk_unit_block_unit_id_unit")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_block")),
        sa.UniqueConstraint(
            "maintenance_id", name=op.f("uq_unit_block_maintenance_id")
        ),
        sa.UniqueConstraint(
            "reservation_item_id", name=op.f("uq_unit_block_reservation_item_id")
        ),
    )
    op.add_column("reservation", sa.Column("starts_on", sa.Date(), nullable=False))
    op.add_column("reservation", sa.Column("ends_on", sa.Date(), nullable=False))
    op.drop_column("reservation", "ends_at")
    op.drop_column("reservation", "starts_at")
    op.create_check_constraint(
        op.f("ck_reservation_valid_period"), "reservation", "ends_on > starts_on"
    )

    op.drop_constraint(
        op.f("ck_reservation_channel_valid"), "reservation", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_reservation_channel_valid"),
        "reservation",
        "channel IN ('web_voice', 'phone', 'telegram')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        op.f("ck_reservation_channel_valid"), "reservation", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_reservation_channel_valid"),
        "reservation",
        "channel IN ('web_voice', 'phone', 'whatsapp')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column(
            "starts_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "reservation",
        sa.Column(
            "ends_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("reservation", "ends_on")
    op.drop_column("reservation", "starts_on")
    op.drop_table("unit_block")
    op.create_check_constraint(
        op.f("ck_reservation_valid_period"), "reservation", "ends_at > starts_at"
    )
    # ### end Alembic commands ###
