"""reservation idempotency key

Revision ID: c28bd31fb9dd
Revises: 57b8f40828f9
Create Date: 2026-09-29 07:20:18.308848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c28bd31fb9dd"
down_revision: str | Sequence[str] | None = "57b8f40828f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation", sa.Column("idempotency_key", sa.String(length=64), nullable=True)
    )
    op.create_unique_constraint(
        "uq_reservation_idempotency_key", "reservation", ["user_id", "idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_reservation_idempotency_key", "reservation", type_="unique")
    op.drop_column("reservation", "idempotency_key")
    # ### end Alembic commands ###
